In [1]:
import numpy as np

In [8]:
a=np.array([1,2,3]) #1-d array
a

array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[1]

2

In [5]:
a[2]

3

In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b.ndim   #to find the dimension of an array

2

In [11]:
a.ndim

1

In [12]:
a.itemsize #to find the byte size of each element in an array(here it is 8,bcoz it is an int)

8

In [13]:
b.itemsize

8

In [14]:
c=np.array(['a','b'])

In [15]:
c

array(['a', 'b'], dtype='<U1')

In [17]:
c.itemsize #character array ,so size of each one is 4

4

In [18]:
c.dtype  #datatype---unicode string

dtype('<U1')

In [19]:
b.dtype

dtype('int64')

In [23]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)

In [25]:
d.itemsize

8

In [27]:
d#converted the datatype to float64

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [28]:
a.size

3

In [30]:
d.size #gives number of elements

9

In [31]:
a.shape

(3,)

In [32]:
b.shape

(3, 3)

In [33]:
d.shape #rows,columns

(3, 3)

In [34]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)

In [36]:
e#converted to complex datatype

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [38]:
z=np.zeros((3,3))#creates 0 matrix

In [39]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
o=np.ones((2,2))

In [41]:
o

array([[1., 1.],
       [1., 1.]])

In [47]:
#in python
l=range(0,11)
print(l[3])

3


In [48]:
#in numpy
r=np.arange(1,5)

In [49]:
r

array([1, 2, 3, 4])

In [50]:
r1=np.arange(1,10,2)

In [51]:
r1

array([1, 3, 5, 7, 9])

In [53]:
l=np.linspace(1,5,10) #prints linearly separated numbers between 1 and 5

In [54]:
l

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
reshap=np.array([[1,2],[4,5],[7,8]])

In [58]:
reshap.shape

(3, 2)

In [60]:
reshap

array([[1, 2],
       [4, 5],
       [7, 8]])

In [59]:
reshap.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])

In [61]:
reshap.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [62]:
reshap.ravel() #flatten the array and make it 1d

array([1, 2, 4, 5, 7, 8])

In [63]:
reshap

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
reshap.min()#returns min element

1

In [65]:
reshap.max()#returns max element

8

In [66]:
reshap.sum()

27

In [67]:
#axis col=0,row=1
reshap.sum(axis=0)#sum of rows

array([12, 15])

In [69]:
reshap.sum(axis=1)#sum of rows

array([ 3,  9, 15])

In [71]:
np.sqrt(reshap)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 2.82842712]])

In [73]:
np.std(reshap)#standard deviation

2.5

In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [76]:
a

array([[1, 2],
       [3, 4]])

In [77]:
b

array([[5, 6],
       [7, 8]])

In [75]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
a*b

array([[ 5, 12],
       [21, 32]])

In [83]:
a=np.array([[1,2]])
b=np.array([[5],[6]])

In [84]:
a

array([[1, 2]])

In [85]:
b

array([[5],
       [6]])

In [81]:
a*b

array([[ 5, 10],
       [ 6, 12]])

In [87]:
b.dot(a)

array([[ 5, 10],
       [ 6, 12]])