In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('/home/adish/Desktop/multilinear_homeprice.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [11]:
df.bedroom.mean()

4.2

In [5]:
import math
median_bedroom=math.floor(df.bedroom.median())
median_bedroom

4

In [6]:
import math
median_bedroom=math.floor(df.bedroom.mean())
median_bedroom

4

In [14]:
df.bedroom.fillna(median_bedroom,inplace=True)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      4.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [16]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df[['price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## price = m1 * area + m2 * bedroom + m3 * age + b

In [25]:
 reg.coef_ #m1,m2,m3

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [18]:
reg.intercept_#value of b

array([221323.0018654])

In [24]:
reg.predict([[3000,2,20]])

array([[539653.72967503]])

In [21]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      4.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [26]:
#price = m1 * area + m2 * bedroom + m3 * age + b
112.06244194*3000+23388.88007794*2+-3231.71790863*20+221323.0018654

539653.72966868