### Numpy --> Numerical Python

## Why NumPy is used in Python?
#### numpy is used for scientific computation in python

#### We use python NumPy array instead of a list because of the below three reasons:

#### 1.Less Memory
#### 2.Fast
#### 3.Convenient

In [1]:
import numpy as np

In [7]:
import sys

#### demonstration of less memory

In [53]:
a=np.array([1,2,3]) #1-d array
print(a.itemsize)
l=[1,2,3]
sys.getsizeof(l[0])

8


28

In [54]:
a[0]

1

In [55]:
a[1]

2

In [56]:
a[2]

3

#### demonstration of speed

In [59]:
import time
l1=[1,2,3]
l2=[0,1,2]
start=time.time()
r=[x*y for x,y in zip(l1,l2)]
end=time.time()
print('Time taken by normal method: '+str(1000*(end-start))+'ms')
print(r)

Time taken by normal method: 2.2165775299072266ms
[0, 2, 6]


In [60]:
n1=np.array([1,2,3])
n2=np.array([0,1,2])
start=time.time()
rr=n1*n2
end=time.time()
print('Time taken by numpy method: '+str(1000*(end-start))+'ms')
print(rr)

Time taken by numpy method: 0.08559226989746094ms
[0 2 6]


In [61]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
b.ndim   #to find the dimension of an array

2

In [64]:
a.ndim

1

In [65]:
a.itemsize #to find the byte size of each element in an array(here it is 8,bcoz it is an int)

8

In [66]:
a=np.array([1,2,3]) #2--->10--->1byte=8bits
import sys

x=1
sys.getsizeof(x)  #size is large bcoz python stores everything as objects ..since it is an object oriented language


28

In [67]:
b.itemsize

8

In [14]:
c=np.array(['a','b'])
lc=['a','b']

In [15]:
c

array(['a', 'b'], dtype='<U1')

In [16]:
lc

['a', 'b']

In [17]:
c.itemsize #character array ,so size of each one is 4

4

In [19]:
sys.getsizeof(lc[0])

58

In [18]:
c.dtype  #datatype---unicode string

dtype('<U1')

In [19]:
b.dtype

dtype('int64')

In [20]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)

In [21]:
d.itemsize

8

In [22]:
d#converted the datatype to float64

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [23]:
a.size

3

In [30]:
d.size #gives number of elements

9

In [31]:
a.shape

(3,)

In [32]:
b.shape

(3, 3)

In [33]:
d.shape #rows,columns

(3, 3)

In [34]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)

In [36]:
e#converted to complex datatype

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [38]:
z=np.zeros((3,3))#creates 0 matrix

In [39]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
o=np.ones((2,2))

In [7]:
o

array([[1., 1.],
       [1., 1.]])

In [27]:
#in python
l=range(0,11)
print(l[1])

1


In [28]:
#in numpy
r=np.arange(1,5)

In [29]:
r

array([1, 2, 3, 4])

In [30]:
r1=np.arange(1,10,2)

In [31]:
r1

array([1, 3, 5, 7, 9])

In [32]:
l=np.linspace(1,5,10) #prints linearly separated numbers between 1 and 5

In [33]:
l

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
reshap=np.array([[1,2],[4,5],[7,8]])

In [36]:
reshap.shape

(3, 2)

In [60]:
reshap

array([[1, 2],
       [4, 5],
       [7, 8]])

In [59]:
reshap.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])

In [61]:
reshap.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [62]:
reshap.ravel() #flatten the array and make it 1d

array([1, 2, 4, 5, 7, 8])

In [63]:
reshap

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
reshap.min()#returns min element

1

In [65]:
reshap.max()#returns max element

8

In [66]:
reshap.sum()

27

In [67]:
#axis col=0,row=1
reshap.sum(axis=0)#sum of rows

array([12, 15])

In [69]:
reshap.sum(axis=1)#sum of rows

array([ 3,  9, 15])

In [71]:
np.sqrt(reshap)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 2.82842712]])

In [73]:
np.std(reshap)#standard deviation

2.5

In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [76]:
a

array([[1, 2],
       [3, 4]])

In [77]:
b

array([[5, 6],
       [7, 8]])

In [75]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
a*b

array([[ 5, 12],
       [21, 32]])

In [37]:
a=np.array([[1,2]])
b=np.array([[5],[6]])

In [40]:
print(a)
print(a.shape)

[[1 2]]
(1, 2)


In [41]:
print(b)
b.shape

[[5]
 [6]]


(2, 1)

In [81]:
a*b

array([[ 5, 10],
       [ 6, 12]])

In [87]:
b.dot(a)

array([[ 5, 10],
       [ 6, 12]])

In [42]:
np.dot(a,b)

array([[17]])